/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package env_middleware */
#pragma once

#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 19 "main.go"
 #include <stdio.h>
 #include <stdlib.h>

 static void myprint(char* s) {
   printf("%s\n", s);
 }

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#include <complex.h>
// typedef _Fcomplex GoComplex64;
// typedef _Dcomplex GoComplex128;
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern __declspec(dllexport) void InitMiddleware(char* serverUrl, char* redisUrl, char* rabbitmqUrl);
extern __declspec(dllexport) void CloseMiddleware();
extern __declspec(dllexport) void GetRawData(double minLat, double minLon, double maxLat, double maxLon, int level);

/* Return type for GetRoutePoints */
struct GetRoutePoints_return {
	int r0;
	double* r1;
	double* r2;
};
extern __declspec(dllexport) struct GetRoutePoints_return GetRoutePoints(double startLongitude, double startLatitude, double stopLongitude, double stopLatitude);
extern __declspec(dllexport) void FreePositionsPointer(double* longitude_arr, double* latitude_arr);
extern __declspec(dllexport) void UpdateObstacle(double latitude, double longitude, char* cause);
extern __declspec(dllexport) void UpdateCrater(double longitude, double latitude, double width, double depth);
extern __declspec(dllexport) double GetAltitude(double longitude, double latitude);

#ifdef __cplusplus
}
#endif
